<?php
/**
 * Spine — default configuration.
 *
 * You normally do NOT edit this file. It is committed to git; anything
 * server-specific or secret belongs in `.env` next to index.php, which
 * overrides every value below. Start from `.env.example`.
 *
 * SQLite is the default and needs no setup. On a server you deploy to from
 * git, set DB_PATH in .env to somewhere outside the deployed folder.
 */

return [
    'app_name'  => 'Spine',
    'tagline'   => 'A circle of people worth knowing.',

    'db' => [
        // 'sqlite'  (recommended, no setup)   |   'mysql'
        'driver'      => 'sqlite',

        'sqlite_path' => __DIR__ . '/../data/spine.sqlite',

        'mysql' => [
            'host' => '127.0.0.1',
            'port' => 3306,
            'name' => 'spine',
            'user' => 'root',
            'pass' => '',
        ],
    ],

    // Leave empty to auto-detect from the request. Set it explicitly
    // (e.g. 'https://spine.example.com') if magic links come out wrong
    // behind a proxy or CDN.
    'base_url' => '',

    // Cookie lifetime for "stay signed in as this person", in days.
    'cookie_days' => 365,
];
